### ISSUE TITLE
Documentation on hackage not available

### ISSUE THREAD

**Issue by hasufell** [MrcJkb/xml-prettify-text#4]
https://hackage.haskell.org/package/xml-prettify-text-1.0.0.2

**Comment by mrcjkb** [comment]
Thanks for the issue.
I guess this is because the build fails on Hackage, although it is successful on my device (in a Nix shell).
I will look into this.

**Comment by hasufell** [comment]
> Thanks for the issue.
> I guess this is because the build fails on Hackage, although it is successful on my device (in a Nix shell).
> I will look into this.

Documentation can be uploaded manually

**Comment by mrcjkb** [comment]
Fixed with version `1.0.0.3`.
